Title: Setting up Python Virtual Environments

# Installing virtualenv

I am assuming here that you have both Mac Ports python27 and python33 installed on your OS X system. If you use brew or fink or something similar, you can make the necessary adjustments in the location of the respective Python framework paths.

## Installing the virtualenv package

To install virtualenv, use either:

~~~bash
$ sudo /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/pip install virtualenv
$ sudo /opt/local/Library/Frameworks/Python.framework/Versions/3.3/bin/pip install virtualenv
~~~

or

~~~bash
$ sudo /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/easy_install install virtualenv
$ sudo /opt/local/Library/Frameworks/Python.framework/Versions/3.3/bin/easy_install install virtualenv
~~~

# Creating virtual environments

## Setting up a Python 2.7 virtual environment

~~~bash
$ cd myproject
$ /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv venv27
~~~

## Setting up a Python 3.3 virtual environment

~~~bash
$ cd myproject
$ /opt/local/Library/Frameworks/Python.framework/Versions/3.3/bin/virtualenv venv33
~~~

# Activating the virtual environment

## Activating the Python 2.7 virtual environment

~~~bash
$ cd myproject
$ . venv27/bin/activate
(venv27)$ python --version
Python 2.7.6
(venv27)$
~~~

## Activating the Python 3.3 virtual environment

~~~bash
$ cd myproject
$ . venv33/bin/activate
(venv33)$ python --version
Python 3.3.4
(venv33)$
~~~

# Deactivating the virtual environment

## Deactivating the Python 2.7 virtual environment

~~~bash
(venv27)$ deactivate
$ python --version
Python 2.7.5
$
~~~

## Deactivating the Python 3.3 virtual environment

~~~bash
(venv33)$ deactivate
$ python --version
Python 2.7.5
$
~~~
